services:
  postgres:
    container_name: postgres
    build:
      context: ./config/postgresql
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}

  app:
    container_name: app
    restart: always
    build:
      context: .
      dockerfile: ./config/application/Dockerfile
    depends_on:
      - postgres
    environment:
      - POSTGRES_HOST=postgres
    ports:
      - ${APP_PORT}:${APP_PORT}
